### ISSUE TITLE
Volunteer Shift Surveys

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#177] opened 2019-05-05 21:48 UTC
User Story:

As a Volunteer, I need a convenient way to provide feedback after a shift ends so that my Volunteer Coordinator can receive timely feedback about the shift.

Acceptance Criteria:

- [ ] The Volunteer Coordinator/Hub Leader has the ability to create and edit a standard after-shift survey.
- [ ] A Volunteer receives a link to the after-shift survey after completing a shift.
- [ ] The Volunteer Coordinator is notified that a Volunteer has completed an after-shift survey.
- [ ] The results of after-shift surveys are compiled and stored within the UI so that they can be perused at the VC's convenience.

**Comment by benjaminwood** [comment] 2019-05-24 16:47
We should consider integrating with [Typeform](https://www.typeform.com) to build this functionality. We don't want to build a survey/form builder into the app ourselves as that is generic functionality. Typeform has nice APIs/integrations that we could hook into to accomplish the notifications, etc.

**Comment by sarahwicks** [comment] 2019-05-29 00:26
@benjaminwood - Sure, as long as there aren't privacy concerns with Typeform, we're open to this option! cc: @SarahOMD @DarcyBlank

**Comment by creaturenex** [comment] 2022-06-06 18:37
Issue closed as this is a duplicate of issue #570 which was closed out with PR #718

**Closed by creaturenex** 2022-06-06 18:37 UTC
Labels: enhancement, medium, Priority 2
